; program to arrange series of 32-bit numbers in ascending/descending order
	AREA SORT,CODE,READONLY
START
	MOV R1,#5 ; INTIALISE COUNTER TO 5(i.e. N=5)
OUTLOOP
	MOV R3,R1
	LDR R0,=0x40000000 ; LOADS THE ADDRESS OF FIRST VALUE
INLOOP
	LDR R2,[R0],#4 ; WORD ALIGN T0 ARRAY ELEMENT
	LDR R4,[R0] ; LOAD SECOND NUMBER
	CMP R4,R2 ; COMPARE NUMBERS
	BCS SKIP ; IF THE FIRST NUMBER IS < THEN GOTO
LOOP2
	STR R2,[R0],#-4 ; INTERCHANGE NUMBER R2 & R0
	STR R4,[R0],#4 ; INTERCHANGE NUMBER R4 & R0
SKIP
	SUBS R3,R3,#1 ; DECREMENT COUNTER
	BNE INLOOP ; LOOP BACK TILL ARRAY ENDS
	SUBS R1,R1,#1
	BNE OUTLOOP
STOP B STOP
	END ; Mark end of file
